# define DEFAULT_SERVER_IP ""
# define DEFAULT_SERVER_CLIENTMAXBODYSIZEMB 1
# define DEFAULT_LOCATION_METHODS "GET POST DELETE"
# define DEFAULT_LOCATION_ROOT ""
# define DEFAULT_LOCATION_UPLOADS "/uploads"
# define DEFAULT_LOCATION_AUTOINDEX false
# define DEFAULT_LOCATION_INDEX "index.html"
# define DEFAULT_LOCATION_REDIRECT ""